version: "3.8"
services:
    app:
        build: .
        env_file: .env
        depends_on:
            - redis
        restart: always
    redis:
        image: redis:7.2.4-alpine
        ports:
            - "6379:6379"
        restart: always
