/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */


export interface paths {
  "/server": {
    /** Get server informations */
    get: operations["getServer"];
  };
  "/town": {
    /** Get all towns */
    get: operations["getTowns"];
  };
  "/town/{identifier}": {
    /** Get town with name or UUID */
    get: operations["getTown"];
  };
  "/nation": {
    /** Get all nations */
    get: operations["getNations"];
  };
  "/nation/{identifier}": {
    /** Get nation with name or UUID */
    get: operations["getNation"];
  };
  "/player": {
    /** Get all players */
    get: operations["getPlayers"];
  };
  "/player/{identifier}": {
    /** Get player with name or UUID */
    get: operations["getPlayer"];
  };
  "/search/{query}": {
    /** Search for player, town or nation by name */
    get: operations["search"];
  };
}

export type webhooks = Record<string, never>;

export interface components {
  schemas: {
    ServerModel: {
      name?: string;
      motd?: string;
      version?: string;
      bukkitVersion?: string;
      tps?: string;
      /** Format: int32 */
      maxPlayers: number;
      onlinePlayers?: (components["schemas"]["NameUuidModel"])[];
    };
    NameUuidModel: {
      name?: string;
      uuid?: string;
    };
    NotFoundResponse: Record<string, never>;
    TownModel: {
      name?: string;
      uuid?: string;
      nation?: components["schemas"]["NameUuidModel"];
      /** Format: int64 */
      joinedNationAt: number;
      mayor?: components["schemas"]["NameUuidModel"];
      board?: string;
      tag?: string;
      formattedName?: string;
      /** Format: int64 */
      registered: number;
      /** Format: int32 */
      balance: number;
      mapColor?: string;
      residents?: (components["schemas"]["NameUuidModel"])[];
      spawn?: components["schemas"]["CoordinatesModel"];
      townBlocks?: (components["schemas"]["CoordinatesModel"])[];
      isNeutral?: boolean;
      isOpen?: boolean;
      isPublic?: boolean;
    };
    NationModel: {
      name?: string;
      uuid?: string;
      king?: components["schemas"]["NameUuidModel"];
      capital?: components["schemas"]["NameUuidModel"];
      board?: string;
      tag?: string;
      formattedName?: string;
      /** Format: int64 */
      registered: number;
      /** Format: int32 */
      balance: number;
      mapColor?: string;
      towns?: (components["schemas"]["NameUuidModel"])[];
      residents?: (components["schemas"]["NameUuidModel"])[];
      enemies?: (components["schemas"]["NameUuidModel"])[];
      allies?: (components["schemas"]["NameUuidModel"])[];
      spawn?: components["schemas"]["CoordinatesModel"];
      isNeutral?: boolean;
      isOpen?: boolean;
      isPublic?: boolean;
    };
    PlayerModel: {
      name?: string;
      uuid?: string;
      /** Format: int64 */
      firstPlayed: number;
      /** Format: int64 */
      lastSeen: number;
      isOnline?: boolean;
      resident?: components["schemas"]["ResidentModel"];
      mmo?: components["schemas"]["MmoModel"];
    };
    CoordinatesModel: {
      /** Format: double */
      x: number;
      /** Format: double */
      y: number;
      /** Format: double */
      z: number;
      type?: string;
      world?: string;
    };
    ResidentModel: {
      town?: components["schemas"]["NameUuidModel"];
      nation?: components["schemas"]["NameUuidModel"];
      friends?: (components["schemas"]["NameUuidModel"])[];
      isMayor?: boolean;
      isKing?: boolean;
      townRanks?: (string)[];
      nationRanks?: (string)[];
      surname?: string;
      title?: string;
      prefix?: string;
      postfix?: string;
      formattedName?: string;
    };
    MmoModel: {
      /** Format: int32 */
      palier: number;
      talents?: (components["schemas"]["TalentModel"])[];
    };
    TalentModel: {
      name?: string;
      /** Format: int32 */
      level: number;
      /** Format: double */
      xp: number;
      /** Format: double */
      xpToNextLevel: number;
      /** Format: double */
      minLevelXp: number;
    };
  };
  responses: never;
  parameters: never;
  requestBodies: never;
  headers: never;
  pathItems: never;
}

export type external = Record<string, never>;

export interface operations {

  getServer: {
    /** Get server informations */
    responses: {
      200: {
        content: {
          "application/json": components["schemas"]["ServerModel"];
        };
      };
    };
  };
  getTowns: {
    /** Get all towns */
    responses: {
      200: {
        content: {
          "application/json": (components["schemas"]["NameUuidModel"])[];
        };
      };
    };
  };
  getTown: {
    /** Get town with name or UUID */
    parameters: {
        /** @description Name or UUID of the town */
      path: {
        identifier: string;
      };
    };
    responses: {
      200: {
        content: {
          "application/json": components["schemas"]["TownModel"];
        };
      };
      404: {
        content: {
          "application/json": components["schemas"]["NotFoundResponse"];
        };
      };
    };
  };
  getNations: {
    /** Get all nations */
    responses: {
      200: {
        content: {
          "application/json": (components["schemas"]["NameUuidModel"])[];
        };
      };
    };
  };
  getNation: {
    /** Get nation with name or UUID */
    parameters: {
        /** @description Name or UUID of the nation */
      path: {
        identifier: string;
      };
    };
    responses: {
      200: {
        content: {
          "application/json": components["schemas"]["NationModel"];
        };
      };
      404: {
        content: {
          "application/json": components["schemas"]["NotFoundResponse"];
        };
      };
    };
  };
  getPlayers: {
    /** Get all players */
    responses: {
      200: {
        content: {
          "application/json": (components["schemas"]["NameUuidModel"])[];
        };
      };
    };
  };
  getPlayer: {
    /** Get player with name or UUID */
    parameters: {
        /** @description Name or UUID of the player */
      path: {
        identifier: string;
      };
    };
    responses: {
      200: {
        content: {
          "application/json": components["schemas"]["PlayerModel"];
        };
      };
      404: {
        content: {
          "application/json": components["schemas"]["NotFoundResponse"];
        };
      };
    };
  };
  search: {
    /** Search for player, town or nation by name */
    parameters: {
        /** @description Search query */
      path: {
        query: string;
      };
    };
    responses: {
      200: {
        content: {
          "application/json": (components["schemas"]["NameUuidModel"])[];
        };
      };
    };
  };
}
